#!/usr/bin/env bash
# Generate THIRD_PARTY_GO.md: a reproducible enumeration of the licenses of
# every Go module linked into the lazydeck binary.
#
# "Reproducible" here means: derived solely from go.mod/go.sum via the
# `go-licenses` tool, so re-running after a dependency bump regenerates an
# accurate notice file with no manual curation. CI/release invoke this so
# published archives always ship current notices.
#
# Requires: go, and github.com/google/go-licenses (installed on demand below).
set -euo pipefail

cd "$(dirname "$0")/.."

OUT="${1:-THIRD_PARTY_GO.md}"
PKG="./cmd/lazydeck"

if ! command -v go-licenses >/dev/null 2>&1; then
  echo "generate-notices: installing go-licenses..." >&2
  GOBIN="$(go env GOPATH)/bin" go install github.com/google/go-licenses@v1.6.0
  GOPATH_BIN="$(go env GOPATH)/bin"
  export PATH="${GOPATH_BIN}:${PATH}"
fi

tmpl="$(mktemp)"
trap 'rm -f "${tmpl}"' EXIT
cat > "${tmpl}" <<'TMPL'
# Third-Party Go Module Licenses

This file is generated by `scripts/generate-notices.sh` from the module graph
of `./cmd/lazydeck`. It lists every Go module linked into the lazydeck binary
together with its license. Do not edit by hand; re-run the script instead.

{{ range . }}
## {{ .Name }}

- License: {{ .LicenseName }}
{{ if .LicenseURL }}- Source: {{ .LicenseURL }}{{ end }}

{{ if .LicenseText }}```
{{ .LicenseText }}
```{{ end }}
{{ end }}
TMPL

echo "generate-notices: writing ${OUT}" >&2
go-licenses report "${PKG}" --template "${tmpl}" > "${OUT}"
echo "generate-notices: done ($(wc -l < "${OUT}") lines)" >&2
